apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins-slave
    spec:
      containers:
      - name: jenkins-slave
        image: jenkinsci/ssh-slave:latest
        imagePullPolicy: Always
        env:
        - name: JENKINS_SLAVE_SSH_PUBKEY
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCl5cHH3ucJ4eCYgp+Xpa43km4NwR9f+b+KndXZEGJAyHcb3nuXK7ze4ARQ9FYL0Y9rxewDWUlmwMmWZtVjJvmp19FptDC5ZNKUDHo0gOz7fAA+852D/bJvedhTMyL6UZF7ZoWvlygaczsoidYojGLAdJh1IiSrO9qe/zPNSQRm9o9LU7u62fAU8oNuDnC4sWHFdg+2ykEvmv9lypYmUfOUL+yjyNfHvhvhodS8vmwe8LVDlO+ZKY5oYj2gYpUBRzslBHT30AynBdV4G+qSR2/UMCWe254xhmmJQkU+vWZoRRhCBLV6mi1fx5CSWm3XhJDWU12hPvKwqGyMC2HE5+Wl jenkins@jenkins.com"